package edu.bethlehem.scinexus.Academic;

public enum Position {
    PROFESSOR, ASSOCIATE_PROFESSOR, ASSISTANT_PROFESSOR, LECTURER, INSTRUCTOR, RESEARCHER, POSTDOC, GRADUATE_STUDENT,
    UNDERGRADUATE_STUDENT, OTHER
}
